export const Types = {
    ADD_TODO: 'ADD_TODO',
    COMPLETED_TODO: 'COMPLETED_TODO',
    DELETE_TODO: 'DELETE_TODO',
    FILTER_TODO: 'FILTER_TODO'
}

export const FilterType = {
    FILTER_ALL: 'FILTER_ALL',
    FILTER_COMPLETED: 'FILTER_COMPLETED',
    FILTER_UN_COMPLETED: 'FILTER_UN_COMPLETED',
}